
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
      
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: facturacionelectronica
      DB_USERNAME: root
      DB_PASSWORD: Sps4_210997

    command: ["sh", "-c", "wait-for-db.sh db php artisan migrate --force && apache2-foreground"]

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Sps4_210997
      MYSQL_DATABASE: facturacionelectronica
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
